MAPS_API_URL = 'https://maps.googleapis.com/maps/api/staticmap?'
FILE_PATH = 'cajeros-automaticos.csv'
BANELCO = 'Banelco'
LINK = 'Link'
INVALID_INPUT = "Sorry, i could not understand '{}', please, try either with 'Banelco' or 'Link'!"
NO_AVAILABLE_ATMS_AROUND = "Sorry! there seems to be no available ATM's nearby"
CODE_DICT = {'BANELCO' : 0, 'LINK' : 1}
R = 6367
MAX_DISTANCE = 500
MAX_TRANSACTIONS = 1000
